### ISSUE TITLE
Slider Links will not open.

### ISSUE THREAD

**Issue by cherrykoda** [enupal/slider#11]
Clicking on any slider, with default slider settings across the board, will not open the link attached to the slide.

The only console output is a warning (attached):
![image](https://user-images.githubusercontent.com/3789834/118892583-1a111400-b8cf-11eb-8dfa-777ad2eb60d1.png)

**Comment by cherrykoda** [comment]
We've stripped out EVERY piece of JS and CSS from the site leaving only the slider's assets that are loaded with the plugin. The links don't work. 

As soon as jQuery was removed, preventing any jQuery from functioning, the links worked. We believe this indicates an issue in the plugin's JS. Possibly a prevent default gone rogue on <a> clicks. 

Our client paid for the plugin and is not happy.

**Comment by cherrykoda** [comment]
Chrome Latest Release, Windows 10

**Comment by andrelopez** [comment]
@cherrykoda We just released Enupal Slider v1.4.0 with a fix to this issue. Please update the plugin and let us know how it goes.

**Comment by cherrykoda** [comment]
@andrelopez on a fresh install with version 1.4

Yes, the links are clickable. But before we get to that point:

- Double Clicking the Slide to edit its information generates a server error. We were able to fix this by editing the slide's redactor config as per this logged issue: https://github.com/enupal/slider/issues/8 (The fix someone posted there works, but needs to be implemented into your codebase)


![image](https://user-images.githubusercontent.com/3789834/119049970-3c6a6680-b98f-11eb-8bf1-4903bd6389a3.png)

- Asset Volumes. When installed the default file system path is wrong, and has to be edited manually. It should be based on Craft 3's @webroot relative paths instead of system pathing. @webroot/assets or @webroot/uploads or @webroot/public etc... 

- Renaming the Slider breaks the slider - gets this error on save. Reloading the page returns user to the listing screen.

![image](https://user-images.githubusercontent.com/3789834/119050442-dcc08b00-b98f-11eb-9974-1a035f5d12e4.png)

- Renaming the slider causes the assets to disappear for that slider, the slider does not create new folder OR move the existing folder/rename existing folder.

![image](https://user-images.githubusercontent.com/3789834/119050212-86ebe300-b98f-11eb-832e-2f3925234b74.png)


**The most critical issue:**

On deployments, Craft's Project config implements the fields, plugin data, etc. but then the plugin install does the same causing duplicate fields, field handles, asset volumes, etc. When removing the duplicates, the database breaks and the entire site goes down. The only way to resolve has been to 'restore project config' from database. The only way to avoid it is to have the craft site set to not utilize the project config feature. _**This is site breaking, and not fixable or workaroundable on our end.**_


Really sorry to tack all of this on the linking issue - but its received no attention on the other issue logs and I have your attention here. Without that project config issue fixed _at a minimum_ this plugin is unusable.

**Comment by andrelopez** [comment]
@cherrykoda thanks for reporting. Let's keep track of these errors on the following tickets:
- Adds support to Craft 3.5 (project config) https://github.com/enupal/slider/issues/10
- Remove/Rename slider issues -> https://github.com/enupal/slider/issues/7

**Comment by cherrykoda** [comment]
Great, thank you!
