### ISSUE TITLE
Edit button and image thumbnails within entry

### ISSUE THREAD

**Issue by justinjordan** [enupal/slider#6]
I had a designer mention that it'd be nice to see some sort of thumbnails/preview and also have a way to easily edit a slider within an entry. Just a button linking back to the slider's edit page would be super convenient.

**Comment by andrelopez** [comment]
Hi @sXule 

Thanks for reaching out. Have you tried the `Sliders` field type? here is the [docs link](https://enupal.com/craft-plugins/enupal-slider/docs/field-type/sliders-field) 

You can add the Sliders field type to your entries. Please let me know if you any question.

Best,
 Andre L

**Comment by justinjordan** [comment]
Sorry, I should've explained better.

I'm able to create a slider field and add it to a section allowing a slider to be attached to an entry. However, once I've added a slider to an entry, there doesn't seem to be a quick way to get to its Edit Slider page from the entry. I have to go to the Enupal Slider panel, find the slider by name, click it, and then edit from there.

I'm merely suggesting having a quick link with the field that links to the Edit Slider page directly. Or better yet, extend the field's dialog to have some quick edit controls, like adding/removing images.

Thanks,
Justin
